# Splitting Dataset & Transforming

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('owid-covid-data.csv')

In [3]:
df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91475 entries, 0 to 91474
Data columns (total 59 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   iso_code                               91475 non-null  object
 1   continent                              87130 non-null  object
 2   location                               91475 non-null  object
 3   date                                   91475 non-null  object
 4   total_cases                            88736 non-null  float64
 5   new_cases                              88735 non-null  float64
 6   new_cases_smoothed                     87728 non-null  float64
 7   total_deaths                           78870 non-null  float64
 8   new_deaths                             79028 non-null  float64
 9   new_deaths_smoothed                    87728 non-null  float64
 10  total_cases_per_million                88261 non-null  float64
 11  new_cases_per_million                  88260 non-null  float64
 12  new_cases_smoothed_per_million         87258 non-null  float64
 13  total_deaths_per_million               78408 non-null  float64
 14  new_deaths_per_million                 78566 non-null  float64
 15  new_deaths_smoothed_per_million        87258 non-null  float64
 16  reproduction_rate                      73551 non-null  float64
 17  icu_patients                           9181 non-null   float64
 18  icu_patients_per_million               9181 non-null   float64
 19  hosp_patients                          11420 non-null  float64
 20  hosp_patients_per_million              11420 non-null  float64
 21  weekly_icu_admissions                  830 non-null    float64
 22  weekly_icu_admissions_per_million      830 non-null    float64
 23  weekly_hosp_admissions                 1446 non-null   float64
 24  weekly_hosp_admissions_per_million     1446 non-null   float64
 25  new_tests                              41217 non-null  float64
 26  total_tests                            40907 non-null  float64
 27  total_tests_per_thousand               40907 non-null  float64
 28  new_tests_per_thousand                 41217 non-null  float64
 29  new_tests_smoothed                     47736 non-null  float64
 30  new_tests_smoothed_per_thousand        47736 non-null  float64
 31  positive_rate                          44964 non-null  float64
 32  tests_per_case                         44367 non-null  float64
 33  tests_units                            49266 non-null  object
 34  total_vaccinations                     12266 non-null  float64
 35  people_vaccinated                      11507 non-null  float64
 36  people_fully_vaccinated                8898 non-null   float64
 37  new_vaccinations                       10310 non-null  float64
 38  new_vaccinations_smoothed              20828 non-null  float64
 39  total_vaccinations_per_hundred         12266 non-null  float64
 40  people_vaccinated_per_hundred          11507 non-null  float64
 41  people_fully_vaccinated_per_hundred    8898 non-null   float64
 42  new_vaccinations_smoothed_per_million  20828 non-null  float64
 43  stringency_index                       77463 non-null  float64
 44  population                             90868 non-null  float64
 45  population_density                     85078 non-null  float64
 46  median_age                             82142 non-null  float64
 47  aged_65_older                          81214 non-null  float64
 48  aged_70_older                          81686 non-null  float64
 49  gdp_per_capita                         82359 non-null  float64
 50  extreme_poverty                        55728 non-null  float64
 51  cardiovasc_death_rate                  82550 non-null  float64
 52  diabetes_prevalence                    84432 non-null  float64
 53  female_smokers                         64630 non-null  float64
 54  male_smokers                           63681 non-null  float64
 55  handwashing_facilities                 41478 non-null  float64
 56  hospital_beds_per_thousand             75274 non-null  float64
 57  life_expectancy                        86861 non-null  float64
 58  human_development_index                82729 non-null  float64
dtypes: float64(54), object(5)
memory usage: 41.2+ MB

In [5]:
#split into 3 dataset (death, vaccine, describe)
list(df.columns)

['iso_code',
 'continent',
 'location',
 'date',
 'total_cases',
 'new_cases',
 'new_cases_smoothed',
 'total_deaths',
 'new_deaths',
 'new_deaths_smoothed',
 'total_cases_per_million',
 'new_cases_per_million',
 'new_cases_smoothed_per_million',
 'total_deaths_per_million',
 'new_deaths_per_million',
 'new_deaths_smoothed_per_million',
 'reproduction_rate',
 'icu_patients',
 'icu_patients_per_million',
 'hosp_patients',
 'hosp_patients_per_million',
 'weekly_icu_admissions',
 'weekly_icu_admissions_per_million',
 'weekly_hosp_admissions',
 'weekly_hosp_admissions_per_million',
 'new_tests',
 'total_tests',
 'total_tests_per_thousand',
 'new_tests_per_thousand',
 'new_tests_smoothed',
 'new_tests_smoothed_per_thousand',
 'positive_rate',
 'tests_per_case',
 'tests_units',
 'total_vaccinations',
 'people_vaccinated',
 'people_fully_vaccinated',
 'new_vaccinations',
 'new_vaccinations_smoothed',
 'total_vaccinations_per_hundred',
 'people_vaccinated_per_hundred',
 'people_fully_vaccinated_per_hundred',
 'new_vaccinations_smoothed_per_million',
 'stringency_index',
 'population',
 'population_density',
 'median_age',
 'aged_65_older',
 'aged_70_older',
 'gdp_per_capita',
 'extreme_poverty',
 'cardiovasc_death_rate',
 'diabetes_prevalence',
 'female_smokers',
 'male_smokers',
 'handwashing_facilities',
 'hospital_beds_per_thousand',
 'life_expectancy',
 'human_development_index']

In [6]:
death = ['iso_code',
 'continent',
 'location',
 'date',
 'total_cases',
 'new_cases',
 'new_cases_smoothed',
 'total_deaths',
 'new_deaths',
 'new_deaths_smoothed',
 'total_cases_per_million',
 'new_cases_per_million',
 'new_cases_smoothed_per_million',
 'total_deaths_per_million',
 'new_deaths_per_million',
 'new_deaths_smoothed_per_million',
 'reproduction_rate',
 'icu_patients',
 'icu_patients_per_million',
 'hosp_patients',
 'hosp_patients_per_million',
 'weekly_icu_admissions',
 'weekly_icu_admissions_per_million',
 'weekly_hosp_admissions',
 'weekly_hosp_admissions_per_million']
df_death = df[death]
df_death.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_death['date'] = pd.to_datetime(df_death['date'])

<ipython-input-7-131eee42f08f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_death['date'] = pd.to_datetime(df_death['date'])

In [8]:
df_death.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91475 entries, 0 to 91474
Data columns (total 25 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   iso_code                            91475 non-null  object
 1   continent                           87130 non-null  object
 2   location                            91475 non-null  object
 3   date                                91475 non-null  datetime64[ns]
 4   total_cases                         88736 non-null  float64
 5   new_cases                           88735 non-null  float64
 6   new_cases_smoothed                  87728 non-null  float64
 7   total_deaths                        78870 non-null  float64
 8   new_deaths                          79028 non-null  float64
 9   new_deaths_smoothed                 87728 non-null  float64
 10  total_cases_per_million             88261 non-null  float64
 11  new_cases_per_million               88260 non-null  float64
 12  new_cases_smoothed_per_million      87258 non-null  float64
 13  total_deaths_per_million            78408 non-null  float64
 14  new_deaths_per_million              78566 non-null  float64
 15  new_deaths_smoothed_per_million     87258 non-null  float64
 16  reproduction_rate                   73551 non-null  float64
 17  icu_patients                        9181 non-null   float64
 18  icu_patients_per_million            9181 non-null   float64
 19  hosp_patients                       11420 non-null  float64
 20  hosp_patients_per_million           11420 non-null  float64
 21  weekly_icu_admissions               830 non-null    float64
 22  weekly_icu_admissions_per_million   830 non-null    float64
 23  weekly_hosp_admissions              1446 non-null   float64
 24  weekly_hosp_admissions_per_million  1446 non-null   float64
dtypes: datetime64[ns](1), float64(21), object(3)
memory usage: 17.4+ MB

In [12]:
df_death.to_excel('DataDeath.xlsx', sheet_name='Sheet 1')

In [16]:
df['date'] = pd.to_datetime(df['date'])

In [17]:
vacc = ['iso_code',
 'continent',
 'location',
 'date',
'new_tests',
 'total_tests',
 'total_tests_per_thousand',
 'new_tests_per_thousand',
 'new_tests_smoothed',
 'new_tests_smoothed_per_thousand',
 'positive_rate',
 'tests_per_case',
 'tests_units',
 'total_vaccinations',
 'people_vaccinated',
 'people_fully_vaccinated',
 'new_vaccinations',
 'new_vaccinations_smoothed',
 'total_vaccinations_per_hundred',
 'people_vaccinated_per_hundred',
 'people_fully_vaccinated_per_hundred',
 'new_vaccinations_smoothed_per_million']
df_vac = df[vacc]
df_vac.head()

,iso_code,continent,location,date,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,...,tests_units,total_vaccinations,people_vaccinated,people_fully_vaccinated,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,new_vaccinations_smoothed_per_million
0,AFG,Asia,Afghanistan,2020-02-24,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df_vac.to_excel('DataVacc.xlsx', sheet_name='Sheet 1')

In [20]:
#split into describe
desc = ['iso_code',
 'continent',
 'location',
 'date',
'stringency_index',
 'population',
 'population_density',
 'median_age',
 'aged_65_older',
 'aged_70_older',
 'gdp_per_capita',
 'extreme_poverty',
 'cardiovasc_death_rate',
 'diabetes_prevalence',
 'female_smokers',
 'male_smokers',
 'handwashing_facilities',
 'hospital_beds_per_thousand',
 'life_expectancy',
 'human_development_index']
df_desc = df[desc]
df_desc.head()

,iso_code,continent,location,date,stringency_index,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-02-24,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,2020-02-25,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,2020-02-26,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,2020-02-27,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,2020-02-28,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511

In [21]:
df_desc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91475 entries, 0 to 91474
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   iso_code                    91475 non-null  object
 1   continent                   87130 non-null  object
 2   location                    91475 non-null  object
 3   date                        91475 non-null  datetime64[ns]
 4   stringency_index            77463 non-null  float64
 5   population                  90868 non-null  float64
 6   population_density          85078 non-null  float64
 7   median_age                  82142 non-null  float64
 8   aged_65_older               81214 non-null  float64
 9   aged_70_older               81686 non-null  float64
 10  gdp_per_capita              82359 non-null  float64
 11  extreme_poverty             55728 non-null  float64
 12  cardiovasc_death_rate       82550 non-null  float64
 13  diabetes_prevalence         84432 non-null  float64
 14  female_smokers              64630 non-null  float64
 15  male_smokers                63681 non-null  float64
 16  handwashing_facilities      41478 non-null  float64
 17  hospital_beds_per_thousand  75274 non-null  float64
 18  life_expectancy             86861 non-null  float64
 19  human_development_index     82729 non-null  float64
dtypes: datetime64[ns](1), float64(16), object(3)
memory usage: 14.0+ MB

In [22]:
df_desc.to_excel('DataDesc.xlsx', sheet_name='Sheet 1')